# Project information
site_name: "Dan IV"
site_description: "Dan IV, Exposee"
site_author: "hoochicken"
site_url: "http://127.0.0.1:8000"

# Copyright
copyright: "&copy; 2024 Mareike Riegel"

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/hoochicken/dan-iv/dictionary"
edit_uri: "https://github.com/hoochicken/dan-iv/dictionary/edit/main/docs_sample"

# Configuration
docs_dir: "docs_sample"
theme:
  name: "readthedocs"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
    - tabs
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJ2ax.js?config=TeX-MML-AM_CHTML"
  - "assets/js/body-quotient-calculator.js"
extra_css:
  - "assets/css/custom.css"
markdown_extensions:
  - markdown_include.include:
      base_path: docs_sample

extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/peaceiris"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/piris314en"

# Page tree
nav:
  - "Home": "index.md"
  - "Reaktionen": "theory/reaktionen.md"
  - "Der Rechner": "calculator.md"
  - "Techniken":
    - "02 Übergang Stand Boden Atemi": "techniques/02-uebergang-stand-boden.md"
    - "04 Atemi": "techniques/04-atemi.md"
    - "05 Nervendruck": "techniques/05-1-nervendruck.md"
    - "05 Würge": "techniques/05-2-wuergen.md"
    - "06 Hebel": "techniques/06-hebel.md"
    - "07 Würfe": "techniques/07-wuerfe.md"
    - "08 Stockabwehr": "techniques/08-stock.md"
    - "09 Messerabwehr": "techniques/09-messerabwehr.md"
    - "10 Gegentechniken": "techniques/10-gegentechniken.md"
    - "11 Weiterführung": "techniques/11-weiterfuehrung.md"
    - "12 Freie SV": "techniques/12-freie-sv.md"
    - "13 Kata": "techniques/13-anwendungsformen-kata.md"
  - "Kata-Theorie":
    - "Definition": "theory/00-1-kata-definition.md"
    - "Stoffsammlung Sutemi Waza": "theory/stoffsammlung.md"
    - "Technik-Ablaeufe allgemein": "theory/technik-ablaeufe.md"
    - "Klein sein": "theory/00-3-klein-sein.md"
  - "Kata":
    - "Übersicht": "kata-techniques/00-uebersicht.md"
    - "Bein": "kata-techniques/01-bein.md"
    - "Körper": "kata-techniques/02-koerper.md"
    - "Arm": "kata-techniques/03-arm.md"
    - "Kopf": "kata-techniques/04-kopf.md"
